name = "kvite"
version = "1.1.0"

description = "A simple KV store in SQLite"
licences = ["Apache-2.0"]
repository = { type = "github", user = "sisou", repo = "kvite" }
links = [
  { title = "SQLite", href = "https://sqlite.org" },
  { title = "lpil/sqlight", href = "https://github.com/lpil/sqlight" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
sqlight = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
